# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    driver: "gd"

    resolvers:
        default:
            web_path: ~


    loaders:
        products_loader:
            filesystem:
                data_root: "%kernel.project_dir%/public/images/products"

    filter_sets:
        cache: ~
        product_list:
            data_loader: products_loader
            quality: 75
            filters:
                thumbnail:
                    size: [450, 450]
                    mode: outbound
        product_detail:
            data_loader: products_loader
            quality: 85
            filters:
                thumbnail:
                    size: [600, 800]
                    mode: outbound
